<?php

namespace Database\Seeders;

use App\Models\Filiere;
use Illuminate\Database\Seeder;

class FiliereSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $filieres = [
            'Management Touristique option Animation touristique',
            'Assistant(e) en cabinet de rééducation réhabilitation',
            'Management Touristique',
            'Management hôtelier',
            'Management hôtelier option Hébergement et Réception',
            'Management hôtelier option Majordome',
            'Management hôtelier option Gouvernante',
            'Habillement option Modélisme Industriel',
            'Habillement option Techniques d\'Habillement Production',
            'Coupe et Couture industrielle',
            'Stylisme Modélisme Industriel',
            'Arts culinaires option Pâtisserie-Chocolaterie',
            'Arts culinaires option Cuisine Marocaine',
            'Arts culinaires option Cuisine Gastronomique',
            'Yield manager',
            'Commis de Cuisine',
            'Mécanicien d\'entretien d\'Aéronef catégorie A1',
            'Aérostructure',
            'Aérostructure option Ajustage montage de cellules d\'aéronefs',
            'Aérostructure option Chaudronnerie Aéronautique',
            'Aérostructure option Matériaux Composites en Aéronautique',
            'Agencement intérieur naval',
            'Agent brancardier',
            'Agent brancardier',
            'Agent commercial',
            'Agent commercial d\'exploitation',
            'Agent Commercial Gare',
            'Agent d’accueil',
            'Agent de maintenance en Industrie des Matériaux de Construction',
            'Agent de Restauration',
            'Agent de traitement de surface automobile',
            'Agent d\'Entretien en Froid et Génie Thermique',
            'Agent d\'Entretien en Froid et Génie Thermique option Frigoriste',
            'Agent d\'Entretien en Froid et Génie Thermique option Génie Climatique',
            'Agent magasinier',
            'Agent Socio-Educatif',
            'Agent visiteur du contrôle technique automobile',
            'Agriculture de Précision',
            'Agro-industrie',
            'Agro-industrie option Machines',
            'Agro-industrie option Procédés',
            'Aide Educateur en Préscolaire',
            'Aide Jardinier',
            'Aide Potier Céramiste',
            'Aide-soignant',
            'Ambulancier',
            'Aménagements et entretien des Espaces Verts',
            'Analyses médicales',
            'Animateur d’équitation',
            'Animation d’une équipe commerciale',
            'Aquaculture',
            'Arts culinaires',
            'Assistant à la vie familiale',
            'Assistant Administratif',
            'Assistant Administratif option Commerce',
            'Assistant Administratif option Comptabilité',
            'Assistant Administratif option Gestion',
            'Assistant de régulation médicale',
            'Assistant Green Keeper',
            'Assistant Vétérinaire',
            'Assistant(e) Gouvernant(e)',
            'Audiovisuel option image',
            'Audiovisuel option montage',
            'Audiovisuel option son',
            'Audit comptable et financier',
            'Automatisation et Instrumentation Industrielle',
            'Auxiliaire de Soins',
            'Auxiliaire de Soins option soins généraux',
            'Auxiliaire de vie sociale',
            'Auxiliaire de vie sociale option personnes âgées',
            'Auxiliaire de vie sociale option personnes en situation d\'handicap',
            'Auxiliaire de vie sociale option petite enfance',
            'Auxiliaire en Santé Bucco-dentaire',
            'Mécanicien d\'entretien d\'Aéronef catégorie Additionnelle B1.1',
            'Mécanicien d\'entretien d\'Aéronef catégorie Additionnelle B2',
            'Bâtiment',
            'Bâtiment option Chef de Chantiers',
            'Bâtiment option Métreur',
            'Bâtiment option Projeteur',
            'Bijouterie',
            'Bijouterie joaillerie',
            'Boucher',
            'Bureau d\'Etude en Construction Métallique',
            'Bureauticien Certifié en Microsoft office Spécialiste',
            'Carrossier Peintre Automobile',
            'Cavalier d’Entrainement des Chevaux de Courses',
            'Certificat de base de sécurité niveau 1',
            'Certificat de base de sécurité niveau 2',
            'Certification Microsoft office Specialist en Access',
            'Certification Microsoft office Specialist en Word',
            'Certification Microsoft office Spécialiste en Excel',
            'Certification Microsoft office Spécialiste en Outlook',
            'Certification Microsoft office Spécialiste en PowerPoint',
            'Certified Cybersecurity Advanced Analyst',
            'Certified Fundamental Cybersecurity Practitioner',
            'Certified Threat Intelligence Associate',
            'Chargé d\'Appui Commercial Bancaire',
            'Chargé de clientèle en Back office',
            'Chaudronnerie Soudure',
            'Chef de chantier BTP',
            'Chef de chantier Travaux Publics',
            'Chef de Rayon Grande Distribution',
            'Chimie Cuir',
            'Chimie Industrielle',
            'Chronométrage',
            'Cloud Security Certified Associate',
            'Coiffeur artistique /Haïr Désigner',
            'Coiffure et Maquillage pour le Cinéma et le Spectacle',
            'Coiffure Femmes',
            'Coiffure Femmes',
            'Coiffure Hommes',
            'Commis de Restaurant',
            'Communication et Relation Clientèle offshore',
            'Community manager',
            'Conducteur de Machines en Plasturgie',
            'Conducteur de Travaux : Travaux Publics',
            'Conducteur d\'Engins BTP',
            'Conducteur Routier de Marchandises',
            'Conducteur Routier de Voyageurs',
            'Confection Industrielle',
            'Conseiller agricole',
            'Conseiller Clientèle en Banque',
            'Construction Métallique',
            'Contrôle et Qualité Textile',
            'Contrôle et réparation des systèmes de freinage',
            'Costume et Habillage pour le Cinéma et le Spectacle',
            'Coupe Cuir',
            'Coupe et Couture',
            'Coupe et Couture',
            'Couture traditionnelle',
            'Créativité et sens de l’innovation dans le secteur THR',
            'Cuisiniste',
            'Cycle de découverte du numérique',
            'Cycle de découverte IA',
            'Décors et Accessoires',
            'Dessinateur de Bâtiment',
            'Développement d’Applications - Python',
            'Développement d’Applications Web et Mobiles (Open source)',
            'Développement de prototype des chemisier et robes',
            'Développement de prototype des vêtements bas',
            'Développement Digital',
            'Développement Digital option Applications Mobiles',
            'Développement Digital option Applications RV/RA',
            'Développement Digital option Web Full Stack',
            'Développement e-commerce',
            'Développement mobile en bootcamp',
            'Développement personnel dans le secteur THR',
            'Développement web en bootcamp',
            'Diagnostic et Electronique Embarquée Automobile',
            'Diagnostic et réparation des boîtes de vitesse automatiques',
            'Diagnostic et réparation des systèmes antipollution automobile',
            'Diagnostic et réparation des systèmes d\'injection Diesel nouvelle génération',
            'Diagnostic et réparation des systèmes d\'injection essence Directe',
            'Diagnostic et réparation des systèmes Multiplexés',
            'Digital Design',
            'Digital Design option UI Designer',
            'Digital Design option UX Designer',
            'Eau et assainissement',
            'Eco-Conducteur du Transport Routier de Marchandises',
            'Eco-Conducteur Routier du Transport de Personnes',
            'E-Commerce',
            'Educateur Spécialisé dans la Petite Enfance',
            'Effets Spéciaux',
            'Efficacité et Audit Energétiques',
            'Electricité de Bâtiment',
            'Electricité de Bâtiment',
            'Electricité de Maintenance Industrielle',
            'Electricité d\'Entretien Industriel',
            'Electricité d\'Installation',
            'Electricité et électronique automobile',
            'Electricité Industrielle',
            'Electromécanique',
            'Electromécanique des engins motorisés',
            'Electromécanique des engins motorisés option Automobile',
            'Electromécanique des Systèmes Automatisés',
            'Emballage et Conditionnement',
            'Embellissement et entretien des espaces verts',
            'Employé de back office bancaire en offshoring',
            'Employé polyvalent grande distribution',
            'Employé(e) d\'étages',
            'Entrepreneuriat',
            'Entretien et Réparation des Machines Cuir',
            'Esthétique',
            'Excellence du service dans les entreprises THR',
            'Exploitation',
            'Exploitation option Logistique',
            'Exploitation option Transport',
            'Fabrication Mécanique',
            'Ferronnerie d\'Art',
            'Fontainier',
            'Froid Commercial et Climatisation',
            'Froid embarqué',
            'Froid industriel',
            'Gastronomie à base de produits du terroir',
            'Génie Civil',
            'Génie Civil option Bâtiments',
            'Génie Civil option Laboratoire BTP',
            'Génie Civil option méthodes en BTP',
            'Génie Civil option Travaux Publics',
            'Génie Climatique',
            'Génie électrique',
            'Génie électrique option Electromécanique des Systèmes Automatisés',
            'Génie électrique option Electronique, Automatisme et Robotique',
            'Génie électrique option Energies renouvelables Eoliennes',
            'Génie électrique option Energies renouvelables solaires',
            'Génie électrique option Mécatronique',
            'Génie Energétique',
            'Génie Energétique option Fluide et énergie',
            'Génie Energétique option Froid Industriel',
            'Génie Energétique option Thermique industrielle',
            'Génie Industriel',
            'Génie Industriel option Gestion de la maintenance',
            'Génie Industriel option Gestion de la production',
            'Génie Mécanique',
            'Génie Mécanique option Bureau d’Etudes en Automobile',
            'Génie Mécanique option Etudes et Méthodes en Construction Métallique',
            'Génie Mécanique option Etudes et Méthodes en Fabrication Mécanique',
            'Génie Mécanique option Méthode FAO Outillage de presse',
            'Génie Mécanique option Usinage outillage de presse',
            'Génie Thermique',
            'Génie Thermique option Froid Commercial et Climatisation',
            'Géomètre Topographe',
            'Gestion de projet de BTP',
            'Gestion des Entreprises',
            'Gestion des Entreprises option Commerce et Marketing',
            'Gestion des Entreprises option Comptabilité et Finance',
            'Gestion des Entreprises option Office Manager',
            'Gestion des Entreprises option Ressources Humaines',
            'Gestion des petits commerces',
            'Gestion d\'unité de production graphique',
            'Gestionnaire de l\'eau potable et de l\'assainissement',
            'Gréeur d\'engins de pêche',
            'Gros œuvre',
            'Gros œuvres',
            'Growth Hacker',
            'Grutier à Tour GMA GME',
            'Habillement',
            'Hacker Ethique Certifié',
            'Haute couture',
            'Hébergement Fondation',
            'Hospitality Manager',
            'Housekeeping',
            'HSE en BTP',
            'Hydraulique industrielle',
            'Hygiène Sécurité Environnement',
            'Industrie 4.0',
            'Industrie Meunière',
            'Infographie',
            'Infographie prépresse',
            'Informatique décisionnelle (Business intelligence)',
            'Infrastructure Digitale',
            'Infrastructure Digitale option Cloud Computing',
            'Infrastructure Digitale option Cyber sécurité',
            'Infrastructure Digitale option IOT',
            'Infrastructure Digitale option Systèmes et Réseaux',
            'Installateur des systèmes photovoltaïques',
            'Installateur fibre optique',
            'Installation et Maintenance Biomédicale',
            'Intelligence Artificielle',
            'Jardinier Qualifié',
            'Leadership dans le secteur THR',
            'Logiciel de réservation informatisé (GDS)',
            'Logistique',
            'Logistique Aéroportuaire',
            'Maçonnerie Polyvalente',
            'Maintenance Automobile',
            'Maintenance de Matériel de Confection',
            'Maintenance des Engins du BTP',
            'Maintenance des engins lourds et véhicules industriels option BTP',
            'Maintenance des instruments électro-navals',
            'Maintenance des Machines et Outillage en Plasturgie',
            'Maintenance des Serres',
            'Maintenance des Véhicules Hybrides/Electriques',
            'Maintenance et Diagnostic Automobile',
            'Maintenance Hôtelière',
            'Maintenance industrielle',
            'Maintenance Mécanique des Navires de Pêche',
            'Maître graisseur',
            'Management Agricole',
            'Management Agricole option Commercialisation des Produits Agricoles (Agrobusiness)',
            'Management Agricole option Gestion des entreprises et Coopératives Agricoles',
            'Management de l’interculturalité dans le secteur THR',
            'Management de projets dans le secteur THR',
            'Management de projets Digitaux',
            'Management des activités touristiques culturelles',
            'Management des activités touristiques en milieu rural',
            'Management des parcs de loisirs',
            'Management hôtelier option Gestion hôtelière',
            'Management Touristique option E-Travel Agency',
            'Management Touristique option Management des destinations durables',
            'Management Touristique option Organisateur d’évènements',
            'Manutentionnaire des Engins Portuaires',
            'Maréchal ferrant d\'équidés',
            'Maroquinerie',
            'Mécanicien de machines de golf',
            'Mécanicien Diéséliste',
            'Mécanicien Général Polyvalent',
            'Mécanicien Régleur de Machines de Confection',
            'Mécanicien Service Rapide Automobile',
            'Mécatronique',
            'Menuiserie',
            'Menuiserie Aluminium',
            'Menuiserie d\'art',
            'Menuiserie Métallique',
            'Menuiserie option Aluminium et Bois',
            'Menuiserie option Ebénisterie',
            'Météorologie',
            'Méthodes en Fabrication Mécanique',
            'Métreur',
            'Moniteur Auto-Ecole',
            'Moniteur d’équitation',
            'Montage Chaussure',
            'Monteur Régleur en Plasturgie',
            'Network and Infrastructure Pentester',
            'NOC Certified Analyst',
            'Oléiculture et Oléotechnie',
            'Opérateur Agricole',
            'Opérateur Agricole option Irrigation Fértigation',
            'Opérateur Agricole option Serriste',
            'Opérateur de Câblage',
            'Opérateur de finition et contrôle',
            'Opérateur de stérilisation',
            'Opérateur en Agro-industrie',
            'Opérateur en Agro-industrie option machines',
            'Opérateur en Agro-industrie option préparateur',
            'Opérateur en Confection de Coiffes et Housses de Véhicules',
            'Opérateur en Dessin Assisté par Ordinateur',
            'Opérateur en Fabrication Mécanique',
            'Opérateur en oléiculture',
            'Opérateur en Valorisation des Dattes',
            'Opérateur logistique',
            'Opérateur Polyvalent Construction Métallique',
            'Opérateur Publication Assistée par Ordinateur (PAO)',
            'Opérateur sur Machines de Base',
            'Opérateur terminal portuaire',
            'Opérateur Topographe',
            'Organisateur d’évènements',
            'Ouvrier Qualifié en électricité',
            'Ouvrier Qualifié en électricité option Electromécanique',
            'Ouvrier Qualifié en électricité option Entretien Electrique',
            'Ouvrier Qualifié en électricité option Installation Electrique',
            'Ouvrier Spécialisé en Coupe et Couture',
            'Palefrenier_Soigneur',
            'Pâtisserie',
            'Patrimoine Design',
            'Patron de barque',
            'Peintre',
            'Peintre décorateur en bâtiment',
            'Peintre Etancheur aéronautique',
            'Peintre Vitrier',
            'Peinture Automobile',
            'Peinture Industrielle',
            'Peinture,Décoration et revêtements spéciaux',
            'Piquage Chaussure',
            'Planification d\'un projet en bâtiment',
            'Plateau et Machinerie',
            'Plâtrier',
            'Plâtrier',
            'Plomberie sanitaire',
            'Plombier chauffagiste',
            'Pompage solaire',
            'Pose de carrelage sol et mur',
            'Pratique du logiciel gestion Paie',
            'Premiers secours',
            'Préparateur des produits de la pêche',
            'Préparation de pharmacie',
            'Préparation Piquage et Piquage Cuir',
            'Production agricole',
            'Production Agricole',
            'Production Agricole option Techniques d\'Horticulture',
            'Production et Qualité en Automobile',
            'Production Graphique',
            'Production Graphique option Impression Digitale',
            'Production Graphique option Support d\'impression et d\'emballage',
            'Production mécanique',
            'Production mécanique option Construction Métallique',
            'Production mécanique option Montage / Ajustage Outillage de presse',
            'Production mécanique option Régleur en Fabrication Mécanique',
            'Programmation Structurée en Python',
            'Programme d\'Innovation Entrepreneuriale : de l\'idée au projet viable',
            'Programmeur Régleur de Machines Outils à Commande Numérique',
            'Prothésiste Dentaire',
            'Qualité Hygiène Sécurité Environnement',
            'Qualité, Hygiène, Sécurité et environnement',
            'Radiologie diagnostique',
            'Ramendeur',
            'Réparateur de véhicule automobile (MAALEM)',
            'Réparateur de Véhicules Automobiles',
            'Réparation des Engins à Moteur (Option: Poids Lourds et Autocars)',
            'Réparation des engins à moteurs option Automobile',
            'Reporter d’images audiovisuel',
            'Responsabilité Sociétale et environnementale des Entreprises (RSE)',
            'Responsable Commercial',
            'Responsable Qualité Habillement',
            'Sculpture sur Bois',
            'Second œuvre',
            'Secrétaire Médicale',
            'Sellier Harnacheur',
            'Service de Restauration \'\'Arts de table\'\'',
            'Session d\'Education à la Sécurité Routière',
            'Snacking',
            'SOC Certified Analyst',
            'Soudage aéronautique',
            'Soudage multi procédés',
            'Soudeur par procédé TIG',
            'Tailleur couturier',
            'Tapis',
            'Tapisserie',
            'Technicien en agroalimentaire option Valorisation des Dattes',
            'Technicien Spécialisé en Diagnostic et Electronique Embarquée',
            'Technicien Spécialisé en Production Graphique',
            'Technicien Spécialisé en Régie et Gestion de Production',
            'Technicien Spécialisé Génie civil',
            'Technicien Spécialisé Géomètre Topographe',
            'Technico Commercial en Matériaux de Construction',
            'Technico-Commercial en Vente de Véhicules et Pièces de Rechange',
            'Techniques Agricoles',
            'Techniques Agricoles option Agriculture Biologique',
            'Techniques Agricoles option Gestion des Sols et systèmes d\'Irrigation',
            'Techniques Agricoles option Production végétale',
            'Techniques de Bois',
            'Techniques de Transformation des Dattes',
            'Techniques Habillement Industrialisation',
            'Technologie des Aliments',
            'Technologie des Aliments option Fabrication',
            'Technologie des Aliments option Hygiène et Qualité',
            'Téléconseiller Centres d\'Appels',
            'Testeur d’intrusions cybernitiques',
            'Testeur de solutions digitales',
            'Textile',
            'Textile option Fabrication et Maintenance Tricotage',
            'Thermique Industrielle',
            'Tissage traditionnel',
            'Traitement de surface et traitement thermique',
            'Transformation des Matériaux Composites',
            'Transformation des produits de la pêche',
            'Transformation et gradation Image de base',
            'Transformation et valorisation des plantes Aromatiques et médicinales',
            'Transformation et valorisation des produits de terroir',
            'Usinage sur Machines Outils à Commande Numérique',
            'Voirie',
            'Web Marketer',
            'Web-Apps security design and Penetration testing',
        ];

        foreach ($filieres as $name) {
            if (!empty($name) && is_string($name)) {
                Filiere::firstOrCreate(['name' => trim($name)]);
            }
        }
    }
}
